### ISSUE TITLE
Indexing GitLab gives 23338 errors

### ISSUE THREAD

**Issue by abitrolly** [sourcegraph/scip-ruby#110] opened 2022-09-16 08:28 UTC
Given GitLab repo checkout at revision 86bd8522d7b530630fd22c81b3d6ffa46a35f559.

https://gitlab.com/gitlab-org/gitlab (which is also available at https://sourcegraph.com/gitlab.com/gitlab-org/gitlab).

v0.1.1 indexer produces 23338 errors on it.
```
$ ./scip-ruby-debug --index-file index.scip . -v 3
...
     3 |Rake::Task['gitlab:license:load'].invoke
        ^^^^
[T333739][2022-09-16T11:20:46.657217] 
./config/initializers/chronic_duration.rb:3: Unable to resolve constant ChronicDuration https://srb.help/5002
     3 |ChronicDuration.raise_exceptions = true
        ^^^^^^^^^^^^^^^
[T333739][2022-09-16T11:20:46.657270] 
./app/serializers/commit_entity.rb:3: The super class API::Entities::CommitWithLink of CommitEntity does not derive from Class https://srb.help/5067
     3 |class CommitEntity < API::Entities::CommitWithLink
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ./lib/api/entities/commit_with_link.rb:5: API::Entities::CommitWithLink defined here
     5 |    class CommitWithLink < Commit
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[T333739][2022-09-16T11:20:46.658575] 
./.git/refs/remotes/patches/mk-update-schema.rb:1: unexpected token tIDENTIFIER https://srb.help/2001
     1 |05d00611723e1d9b61e7e344dcde63adef33ea59
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[T333739][2022-09-16T11:20:46.658742] 
3: File Not Found https://srb.help/1004
[T333739][2022-09-16T11:20:48.894211] Errors: 23338 
```

I am not sure how to report all of that. Maybe it is just some config parsing problem.

EDIT: The last error is suspicious - it looks like the indexer descends into `.git` directory that is normally ignored by other tools.

**Comment by varungandhi-src** [comment] 2022-09-16 13:03
The code isn't using Sorbet as far as I can tell; there is no mention of Sorbet in the [Gemfile.lock](https://gitlab.com/gitlab-org/gitlab/-/blob/master/Gemfile.lock). Is that right?

scip-ruby only supported indexing code that is "Sorbet-clean" (using `# typed: false` is fine but there shouldn't be any errors). From the README:

> scip-ruby builds on top of the [Sorbet](https://github.com/sorbet/sorbet) type-checker. If you use Sorbet in your project, follow the instructions below. Projects which do not use Sorbet are not supported.

**Comment by abitrolly** [comment] 2022-09-16 14:32
Looks like it isn't - https://gitlab.com/gitlab-org/quality/team-tasks/-/issues/153

Why it needs to be present in `Gemfile`? Does it mean it will execute actual code to get typing information? Meaning that the analysis is not static.

**Comment by varungandhi-src** [comment] 2022-09-16 16:11
(At the risk of repeating information you already know) Gemfiles can contain both runtime dependencies and development dependencies. So the inference of:

> Does it mean it will execute actual code to get typing information? Meaning that the analysis is not static.

Is not quite right. Sorbet (the type-checker) runs on a local dev machine (or CI). Yes, Sorbet has a runtime component too to properly ensure type safety for checks which can't be done at compile-time. You can think of this as similar to statically typed languages which usually have machinery for performing downcasts baked into the language runtime (see [the docs](https://sorbet.org/docs/runtime) for more details).

scip-ruby does not utilize Sorbet's runtime component in any way, it is fully static.

> Why it needs to be present in Gemfile?

Sorbet does not need to be present in the Gemfile, but I looked there because normally you'd want the Sorbet version in the Gemfile.lock. For example, if you see a type error in CI, you'd want to have the same version locally to reproduce the issue. Having the version be tracked in the Gemfile(.lock) like every other development dependency would be a good way to do that.

> Looks like it isn't - [gitlab.com/gitlab-org/quality/team-tasks/-/issues/153](https://gitlab.com/gitlab-org/quality/team-tasks/-/issues/153)

OK, so I'm going to close this. If you running into errors with scip-ruby on a codebase that is Sorbet-clean, please feel free to open a new issue.

**Closed by varungandhi-src** 2022-09-16 16:11 UTC
Labels: wontfix

**Comment by abitrolly** [comment] 2022-09-17 08:54
That Sorbet. Does it have some defaults like not visiting the `.git` dir?

Could `scip-ruby` detect that there is not `sorbet/` dir and use these defaults? It already provides information about Ruby symbols https://sourcegraph.com/gitlab.com/gitlab-org/gitlab so perhaps defaults could improve the results without commenting all the code.

**Comment by varungandhi-src** [comment] 2022-09-18 23:06
> That Sorbet. Does it have some defaults like not visiting the .git dir?

That's not a default, but you can pass `--ignore /.git` to get that behavior. https://sorbet.org/docs/cli#including-and-excluding-files

> Could scip-ruby detect that there is not sorbet/ dir and use these defaults?

It should be easy to add a default ignore for `.git`. I don't think that's the main issue here though, is it? (Or is your point that we should make that improvement somewhat independently of the original problem you're running into?)

> It already provides information about Ruby symbols [sourcegraph.com/gitlab.com/gitlab-org/gitlab](https://sourcegraph.com/gitlab.com/gitlab-org/gitlab)

I don't see any scip-ruby uploads for that repo; the current list of symbols of powered by ctags. If you see a hover that says 'search-based', that means the information is not coming from scip-ruby.

Just to clarify things because I think there was a misunderstanding in the linked thread in GitLab. scip-ruby is an opt-in tool which provides code intelligence on Sourcegraph. We're not automatically running it for a large amount of Ruby code because much of it isn't typed.

I have a separate issue open for investigating what we can do if you don't have any annotations (or are using `# typed: false`) https://github.com/sourcegraph/scip-ruby/issues/30, and that is next on my TODO list after finishing some initial feature work and existing PRs, but I haven't gotten to it yet.
