### ISSUE TITLE
Bump `sorbet` version

### ISSUE THREAD

**Issue by abitrolly** [sourcegraph/scip-ruby#119] opened 2022-09-22 18:27 UTC
### Problem

I am getting the same issue as described here https://github.com/Shopify/tapioca/issues/1108

```
sorbet/rbi/gems/reline@0.3.1.rbi:863: Malformed type declaration. Generic class without type arguments Reline::History https://srb.help/5045
     863 |Reline::HISTORY = T.let(T.unsafe(nil), Reline::History)
                                                 ^^^^^^^^^^^^^^^
```

### Suggested solution

It seems to be fixed in recent Sorbet versions https://github.com/sorbet/sorbet/pull/6207

**Comment by varungandhi-src** [comment] 2022-09-25 23:40
Thanks for flagging. The patch landed on Aug 10, and our latest merge from upstream (https://github.com/sourcegraph/scip-ruby/pull/104) was on Sept 13, so I seem to have done something wrong with the merge.

**Comment by varungandhi-src** [comment] 2022-09-26 01:31
The merge was fine, but the merge happened ~13 days back, whereas the last release was done ~18 days back. I've cut a new release (v0.1.2) which includes this fix. Please double-check if that fixes your issue.

**Closed by varungandhi-src** 2022-09-26 01:31 UTC
Labels: enhancement

**Comment by abitrolly** [comment] 2022-09-27 06:52
I had to add `;` to download line [here](https://github.com/sourcegraph/scip-ruby/releases/tag/scip-ruby-v0.1.2) to make it work on Linux.
```diff
TAG=scip-ruby-v0.1.2 \
OS="$(uname -s | tr '[:upper:]' '[:lower:]')" \
-RELEASE_URL="https://github.com/sourcegraph/scip-ruby/releases/download/$TAG" \
+RELEASE_URL="https://github.com/sourcegraph/scip-ruby/releases/download/$TAG"; \
curl -L "$RELEASE_URL/scip-ruby-x86_64-$OS" -o scip-ruby && \
chmod +x scip-ruby
```
I was still getting the error until I removed `sorbet/rbi/gems/reline@0.3.1.rbi` file. Now I need to remember how did I get this file in the first place. Probably it was some `tapioca` command.

**Comment by varungandhi-src** [comment] 2022-09-27 10:45
Hmm... are you sure about the extra `;`? 🤔 I don't see why it would be needed...

Wrt the `rbi` file, if you file a separate issue with reproduction steps, I can try to investigate (it doesn't seem like a scip-ruby issue but hard to tell based on the description).

**Comment by abitrolly** [comment] 2022-09-30 12:58
> Hmm... are you sure about the extra `;`? thinking I don't see why it would be needed...

Yes. It is needed. Maybe it is how `Zsh` behaves, but it doesn't expand variable for the same command.
```bash
✗ XX=xx echo $XX;

✗ XX=xx; echo $XX;
xx
```

**Comment by varungandhi-src** [comment] 2022-09-30 14:40
Ugh, this seems to be a difference between fish and bash/zsh. I'll update the docs, thanks for flagging.

**Comment by abitrolly** [comment] 2022-10-02 06:19
It would also be nice to report `scip-ruby` version. Right now it reports the version of Sorbet.

```
$ scip-ruby --version
Sorbet typechecker 0.5.1 git 148adb915eab2c032b2e5e986f35502a27b34b9f debug_symbols=true clean=1 
```

**Comment by varungandhi-src** [comment] 2022-10-03 11:14
Good point, filed https://github.com/sourcegraph/scip-ruby/issues/127
